-- script that creates a database and a table
-- id: int unique autogenerated not null and primary key
-- state_id: int not null fK reference to id of states table
-- name: varchar(256) not null

CREATE DATABASE IF NOT EXISTS `hbtn_0d_usa`;
CREATE TABLE IF NOT EXISTS `hbtn_0d_usa`.`cities` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`state_id` INT NOT NULL,
	`name` VARCHAR(256) NOT NULL, 
	FOREIGN KEY (`state_id`) REFERENCES states(`id`),
	PRIMARY KEY (`id`)
	);


